#!/bin/bash

export SAI_HOME=/home/sai

export LD_LIBRARY_PATH=/usr/lib64:/usr/local/lib64:${SAI_HOME}/tools/lib64:.
export LIBPATH=${LD_LIBRARY_PATH}
export PATH=/public/anaconda2/bin:${SAI_HOME}/project/bin:${SAI_HOME}/project/sbin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/public/anaconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/mysql/bin

export PYTHONPATH=${SAI_HOME}/project/src/common:${SAI_HOME}/project/src:/usr/local/lib64/pkgconfig:/usr/lib64/pkgconfig:/usr/local/apr/lib/pkgconfig

export PHOME=${SAI_HOME}/project
export DATA=${SAI_HOME}/project/data
export LOG=${SAI_HOME}/project/log

export LANG=zh_CN.utf8

today=$(date +%Y%m%d)
log=${LOG}/AUTO_kday.out
err=${LOG}/AUTO_kday.err


exec 3>${log}
exec 4>${err}
exec 1>&3
exec 2>&4


#
# step. get  k-day data
cd ${PHOME}/src/dayend && time python k_day.py

## step. calc k-day tech
##cd ${PHOME}/src/dayend && time python k_day_tech.py


# thrive.py -- three-five line @2017-9-3
# disabled at 2018-9-19
#cd ${PHOME}/src/thrive && time python thrive.py

# pre-thrive.py -- pre-three-five line @2017-9-5
cd ${PHOME}/src/pre_thrive && time python pre_thrive.py


# thrap.py -- three line with loop conditoin @2017-9-20
#cd ${PHOME}/src/thrap && time python thrap.py


# sao.py -- saohuo
cd ${PHOME}/src/decision && time python sao.py

# 2018 #
# wine -- wine-field
cd ${PHOME}/src/wine && time python myrun.py



## index  data 
# 2018-6-22 re-start 放在最后，这样邮件就会在最上面
cd ${PHOME}/src/dayend && time python  k_index_day.py
# 2018-9-19 disable
#cd ${PHOME}/src/report && time python  index.py


exec 3>&-
exec 4>&-

echo "shell: [${today}] run DAILY succeeds."

#autokday
