#!/bin/bash

export LD_LIBRARY_PATH=/usr/lib64:/usr/local/lib64:/p1/sai/tools/lib64:.:/usr/local/mysql/lib
export LIBPATH=${LD_LIBRARY_PATH}
export PATH=/anaconda2/bin:/p1/sai/project/bin:/p1/sai/project/sbin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/p1/sai/bin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/games:.:/usr/local/mysql/bin

export PYTHONPATH=/p1/sai/project/src/common

export PHOME=/p1/sai/project
export DATA=/p1/sai/project/data
export LOG=/p1/sai/project/log

export LANG=zh_CN.utf8


today=$(date +%Y%m%d)
log=${LOG}/kday_${today}.log
err=${LOG}/kday_${today}.err


exec 3>${log}
exec 4>${err}
exec 1>&3
exec 2>&4



#nohup python k_day.py &
# 1. get  k-day data
cd ${PHOME}/src/dayend && time python k_day.py

# 3. calc k-day tech # back to end 2017-6-11
cd ${PHOME}/src/dayend && time python k_day_tech.py

# 2.1 apply the rules: K only, not depend on MACD
cd ${PHOME}/src/decision && time python k1.py

# 2017-6-18
cd ${PHOME}/src/decision && time python k2.py

# 2017-6-27
#cd ${PHOME}/src/decision && time python m1.py

# 2.2 apply the rules: volume only, not depend on MACD 2016/12/4
cd ${PHOME}/src/decision && time python v1.py

# 2.21 super volume-rate, 2017-2-11
cd ${PHOME}/src/decision && time python v2.py

# 2.22. v4.py top(vol) && top(close), 2017-6-25
cd ${PHOME}/src/decision && time python v4.py

# 2.3 apply the rules: fupai
cd ${PHOME}/src/decision && time python d1.py

# 2.4 apply the rules: zhenfu
cd ${PHOME}/src/decision && time python p1.py

# 2.5 apply the rules: zhenfu
cd ${PHOME}/src/decision && time python p2.py

# 2.6 apply the rules: zhenfu 2017-3-10
cd ${PHOME}/src/decision && time python p3.py


# 2.7 apply the rules: hengpan 2017-4-16
cd ${PHOME}/src/decision && time python break.py

# 2.8 apply the rules: rename 2017-5-29
cd ${PHOME}/src/decision && time python name.py

# 2.9 apply the rules: diliang 2017-6-11
cd ${PHOME}/src/decision && time python sao.py



# 4. apply the rules: need MACD: cross ma*5
#cd ${PHOME}/src/decision && time python ma_cross5.py

# 5. apply the rules: dadan3 back ma5 or cross ma10
cd ${PHOME}/src/decision && time python good.py 

#
# 21. get  k-30min data @2017-6-18
cd ${PHOME}/src/dayend && time python k_unit.py

# 23. v3.py @2017-6-18
cd ${PHOME}/src/decision && time python v3.py

# 24. flag.py @2017-7-13
cd ${PHOME}/src/decision && time python flag.py

# 25. flag.py @2017-7-18
cd ${PHOME}/src/decision && time python cwh.py


exec 3>&-
exec 4>&-

echo "shell: run k_day.py succeeds."

#autokday
