#!/bin/bash

export LD_LIBRARY_PATH=/usr/lib64:/usr/local/lib64:/p1/sai/tools/lib64:.:/usr/local/mysql/lib
export LIBPATH=${LD_LIBRARY_PATH}
export PATH=/anaconda2/bin:/p1/sai/project/bin:/p1/sai/project/sbin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/p1/sai/bin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/games:.:/usr/local/mysql/bin

export PYTHONPATH=/p1/sai/project/src/common

export PHOME=/p1/sai/project
export DATA=/p1/sai/project/data
export LOG=/p1/sai/project/log

export LANG=zh_CN.utf8


today=$(date +%Y%m%d)
log=${LOG}/rt_u15m_${today}.out
err=${LOG}/rt_u15m_${today}.err


exec 3>${log}
exec 4>${err}
exec 1>&3
exec 2>&4


cd ${PHOME}/src/realtime

nohup python rt_u15m.py &

exec 3>&-
exec 4>&-

echo "shell: run rt_u15m.py succeeds."

#autou15m
