#!/bin/bash

export SAI_HOME=/home/sai3

export LD_LIBRARY_PATH=/usr/lib64:/usr/local/lib64:${SAI_HOME}/tools/lib64:.
export LIBPATH=${LD_LIBRARY_PATH}
export PATH=/home/public/anaconda3/bin:${SAI_HOME}/project/bin:${SAI_HOME}/project/sbin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/mysql/bin

export PYTHONPATH=${SAI_HOME}/project/src/common:${SAI_HOME}/project/src:/usr/local/lib64/pkgconfig:/usr/lib64/pkgconfig:/usr/local/apr/lib/pkgconfig

export PHOME=${SAI_HOME}/project
export DATA=${SAI_HOME}/project/data
export LOG=${SAI_HOME}/project/log

export LANG=zh_CN.utf8


today=$(date +%Y%m%d)
log=${LOG}/AUTO_INFO.out
err=${LOG}/AUTO_INFO.err


exec 3>${log}
exec 4>${err}
exec 1>&3
exec 2>&4

# 1. get  stock-basic
cd ${PHOME}/src/dayend && time python get_stock_basic.py


# 2. get xsg info
cd ${PHOME}/src/dayend && time python get_xsg.py


exec 3>&-
exec 4>&-

echo "shell: [${today}] run INFO succeeds."

#autoinfo
