#!/bin/bash

export LD_LIBRARY_PATH=/usr/lib64:/usr/local/lib64:/p1/sai/tools/lib64:.:/usr/local/mysql/lib
export LIBPATH=${LD_LIBRARY_PATH}
export PATH=/anaconda2/bin:/p1/sai/project/bin:/p1/sai/project/sbin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/p1/sai/bin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/games:.:/usr/local/mysql/bin

export PYTHONPATH=/p1/sai/project/src/common

export PHOME=/p1/sai/project
export DATA=/p1/sai/project/data
export LOG=/p1/sai/project/log

export LANG=zh_CN.utf8


today=$(date +%Y%m%d)
log=${LOG}/cross_${today}.log
err=${LOG}/cross_${today}.err


exec 3>${log}
exec 4>${err}
exec 1>&3
exec 2>&4


cd ${PHOME}/src/decision

#nohup python k_day.py &
# 1. cross 6 ma
time python ma_cross6.py

# 2. cross 5 ma -- 2016-11-27
time python ma_cross5.py


exec 3>&-
exec 4>&-

echo "shell: run ma_cross.py succeeds."

#autocross
